### ISSUE TITLE
Hard size limit

### ISSUE THREAD

**Issue by DLMousey** [lostdesign/teamotes#31]
Especially during high periods of activity, chats with Teamotes users in them become unreadable very quickly thanks to 960+px images being constantly spammed one after another. Seems to be unique to discord that one user starts spamming these, another users sees they're getting away with it and joins in, suddenly chat is unusable for anyone else.

A hard limit on size would help control this spamming, perhaps down to 128px so the images coming out of Teamotes are more in line with slack/discord emoji sizes.

**Comment by stinja** [comment]
yes pls. thank you

**Comment by lostdesign** [comment]
Resizing will be a thing with #6 - would not really force anything in teamotes itself, as its not meant for just emotes. This is more a matter of the responsible use of emotes/not spamming in each communities and should be addressed in the community instead :p

**Comment by DLMousey** [comment]
With respect i strongly disagree. An automatic hard size limit is desperately needed, it's the biggest potential factor for abuse, reading through offtopic on devcord presents an almost unending stream of abuse of the application, adding the biggest possible image the user can get their hands on and spamming it again.
and again.
and again.
and again.
and again.

You could ban these users but what happens when another 30 pop up to take their place? At that point you're in a situation where you're trying to stop the sea making the sand wet - and quite frankly a lot of us are getting really fed up of trying to find a discussion hidden between endless streams of teamotes spam.
