### ISSUE TITLE
Analyze different clipboard approaches

### ISSUE THREAD

**Issue by lostdesign** [lostdesign/teamotes#9]
Check if https://www.electronjs.org/docs/api/clipboard is better than the current used browser Clipboard API.

- [x] check electrons clipboard api

- [x] check https://github.com/sindresorhus/clipboardy

- [x] check native binaries for clipboard to mitigate alpha/gif issue

**Comment by lostdesign** [comment]
https://stackoverflow.com/questions/14934327/how-to-get-animated-gif-image-from-browser-clipboard-api
https://docs.microsoft.com/en-us/windows/win32/dataxchg/standard-clipboard-formats
https://stackoverflow.com/questions/7778539/copy-to-clipboard-in-node-js/13735363#13735363

**Comment by ahmedwalid05** [comment]
- ### Clipboardy : 
	- [Doesn't support images ](https://github.com/sindresorhus/clipboardy/issues/64)
- ### Electron API: 
	- [ Supports images jpg/png (ico on windows only)](https://www.electronjs.org/docs/api/native-image)
	- [Gif support yet to come](https://github.com/electron/electron/issues/5078)

- ### Chrome's Clipboard API: 
   - [Clipboard api only supports png](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#Browser_compatibility)
